### ISSUE TITLE
Gros malaise dans le client

### ISSUE THREAD

**Issue by Erwannus** [ShawnHeyli/friendlyfire#4]
```
[plugin:vite:import-analysis] Failed to resolve import "@tauri-apps/plugin-store" from "src/main.ts". Does the file exist?
/home/erwann/Documents/friendlyfire/client/src/main.ts:1:22
1  |  import { Store } from "@tauri-apps/plugin-store";
   |                         ^
2  |  import { initStoredValues, restoreStoreValues } from "./store";
3  |  import { initPingStatus } from "./ping";
    at TransformPluginContext._formatError (file:///home/erwann/Documents/friendlyfire/client/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49159:41)
    at TransformPluginContext.error (file:///home/erwann/Documents/friendlyfire/client/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49154:16)
    at normalizeUrl (file:///home/erwann/Documents/friendlyfire/client/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:63936:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///home/erwann/Documents/friendlyfire/client/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:64068:39
    at async Promise.all (index 0)
    at async TransformPluginContext.transform (file:///home/erwann/Documents/friendlyfire/client/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:63995:7)
    at async PluginContainer.transform (file:///home/erwann/Documents/friendlyfire/client/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49000:18)
    at async loadAndTransform (file:///home/erwann/Documents/friendlyfire/client/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51822:27)
    at async viteTransformMiddleware (file:///home/erwann/Documents/friendlyfire/client/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:61776:24
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.ts.
```

**Comment by ShawnHeyli** [comment]
t'as bien fait le bun install dans client/ ?

**Comment by Erwannus** [comment]
non :clown_face:
